### ISSUE TITLE
Why not provide a static binary?

### ISSUE THREAD

**Issue by tobimensch** [KDAB/Qt4to5#2]
Hi,

I need this tool just once. I'm not eager to go through all the  trouble of compiling it with llvm and all of that, since I also read somewhere that there are compile errors at the moment.

I don't understand why this tool isn't provided as a simple static binary?

I would really be grateful!

**Comment by dfaure-kdab** [comment]
Because we (KDAB) don't officially support this tool, and the person writing it left the company since (note how the last changes are from 2012, I'm not sure this even compiles anymore).
I consider this tool mostly an experiment with the clang library, rather than a finished product.

We do however provide Qt4-Qt5 migration services (using a whole set of other tools), if you're interested.

**Comment by tobimensch** [comment]
I understand. I just wanted to port an open-source tool,  which has also been abandoned by someone else. I'm a private person and I'm not intending to pay money to get something ported from which I'll not profit in any way.

**Comment by dfaure-kdab** [comment]
OK, I see. In that case, your best option is to port by hand, using the information that is available on the internet: in the Qt documentation, but also in our blog: https://www.kdab.com/porting-from-qt-4-to-qt-5/
